FROM alpine

RUN mkdir /japura-www
COPY . /japura-www/
WORKDIR /japura-www/
EXPOSE 8080

ENV GO_ENV production
ENV MONGODB mongodb
ENV DATABASE japura
ENV CLIENTSECRET somesecret
ENV CLIENTID someid

CMD ["./japuraV2"]


